name       : netcdf-c
version    : 4.8.0
release    : 3
source     :
    - https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.8.0.tar.gz : aff58f02b1c3e91dc68f989746f652fe51ff39e6270764e484920cb8db5ad092
license    : BSD-3-Clause
component  : programming.library
homepage   : https://www.unidata.ucar.edu/software/netcdf/
summary    : Network Common Data Form (NetCDF)
description: |
    NetCDF (Network Common Data Form) is a set of software libraries and machine-independent data formats that support the creation, access, and sharing of array-oriented scientific data. It is also a community standard for sharing scientific data.
builddeps  :
    - pkgconfig(hdf5_hl)
    - pkgconfig(libcurl)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
